Repository dnd-side-project/dnd-6th-7-worry-record-service, pull requests merged in 2022-02, with the labels that each got.

#27 CI/CD: Kakao Login Refactoring
  .github/workflows/docker.yml
  .gitignore
  README.md
  src/main/java/dnd/project/dnd6th7worryrecordservice/config/AppConfig.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/config/SecurityConfig.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/controller/KakaoController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/user/UserRepository.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/UserRequestDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/jwt/JwtUtil.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/KakaoService.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/UserService.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/sql/ddl.sql
  src/test/java/dnd/project/dnd6th7worryrecordservice/jwt/JwtUtilTest.java
  src/test/java/dnd/project/dnd6th7worryrecordservice/service/UserServiceTest.java
  src/test/java/dnd/project/dnd6th7worryrecordservice/singletonTest/RepositorySingletonTest.java
Labels: CI/CD

#28 CI/CD: refactor: delete no test & add application.yml
  .github/workflows/docker.yml
  src/main/resources/application.yml
Labels: CI/CD

#29 CI/CD: Set Jpa DataBase
  src/main/resources/application.yml
Labels: CI/CD

#30 CI/CD: Delete h2 setting code
  src/main/resources/application.yml
Labels: CI/CD

#31 KakaoController Swagger 세부정보 추가
  src/main/java/dnd/project/dnd6th7worryrecordservice/config/SwaggerConfig.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/controller/KakaoController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/user/User.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/jwt/JwtPayloadDto.java
  src/test/java/dnd/project/dnd6th7worryrecordservice/singleton/SingletonTest.java
Labels: 기능 개선

#33 CI/CD: EB 버전 오류 해결
  .github/workflows/docker.yml
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/HealthCheck.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/config/SecurityConfig.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/config/SwaggerConfig.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/controller/KakaoController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/user/User.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/jwt/JwtPayloadDto.java
  src/main/resources/application.yml
  src/test/java/dnd/project/dnd6th7worryrecordservice/singleton/SingletonTest.java
Labels: CI/CD

#34 refactor: S3 원인 해결
  build.gradle
Labels: CI/CD

#35 CI/CD: refactor: EB 버전 변경
  .github/workflows/docker.yml
Labels: CI/CD

#36 CI/CD: refactor: EB 버전 변경
  .github/workflows/docker.yml
Labels: CI/CD

#43 CI/CD: secret manager name 변경
  .github/workflows/docker.yml
  src/main/resources/bootstrap.yml
Labels: CI/CD

#47 CI/CD: EB 초기화
  .github/workflows/docker.yml
  Dockerrun.aws.json
Labels: CI/CD

#52 CI/CD: fix: UserResponseDto가 userId도 담도록 수정
  .gitignore
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/KakaoController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/UserResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/KakaoService.java
Labels: CI/CD

#56 CI/CD: refactor: UserDto 위치 변경
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/KakaoController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/jwt/JwtPayloadDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/user/UserRequestDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/user/UserResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/jwt/JwtUtil.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/KakaoService.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/UserService.java
Labels: CI/CD

#61 CI/CD: fix: KakaoController 이름 변경 및 EndPoint 수정
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/AuthController.java
Labels: CI/CD

#65 Feature/59 worry locker
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/config/SecurityConfig.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/config/SwaggerConfig.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/config/WebConfig.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/category/CategoryRepository.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/user/User.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/worry/Worry.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/worry/WorryRepository.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/WorryChatResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/WorryCntResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/WorryRequestDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/WorryResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/WorryReviewModifyRequestDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/WorryReviewResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/CategoryService.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/UserService.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/WorryService.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/sql/ddl.sql
Labels: 기능 구현

#69 feat: 걱정 보관함 기능 구현 - 홈, 걱정 작성, 요즘 걱정
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/worry/Worry.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/worry/WorryRepository.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/WorryRequestDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/request/WorryRequestDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/request/WorryReviewModifyRequestDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryChatResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryCntResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryHomeResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryReviewResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/WorryService.java
Labels: 기능 구현

#70 CI/CD: feat: 걱정 보관함 기능 구현 - 홈, 걱정 작성, 요즘 걱정
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/worry/Worry.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/worry/WorryRepository.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/WorryRequestDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/request/WorryRequestDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/request/WorryReviewModifyRequestDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryChatResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryCntResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryHomeResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryReviewResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/WorryService.java
Labels: CI/CD

#71 fix: SecurityConfig 코드 주석 #8
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/config/SecurityConfig.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/category/Category.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/worry/Worry.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/sql/ddl.sql
Labels: 코드 수정

#72 Feature/59 worry locker
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/config/SecurityConfig.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/category/Category.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/worry/Worry.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/sql/ddl.sql
Labels: 코드 수정

#73 CI/CD: fix: SecurityConfig 코드 주석 #8
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/config/SecurityConfig.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/category/Category.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/worry/Worry.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/sql/ddl.sql
Labels: CI/CD

#74 fix: SecurityConfig 수정 #8
  src/main/java/dnd/project/dnd6th7worryrecordservice/config/SecurityConfig.java
Labels: 코드 수정

#75 fix: SecurityConfig 수정 #8
  src/main/java/dnd/project/dnd6th7worryrecordservice/config/SecurityConfig.java
Labels: 코드 수정

#76 CD/CD: fix: SecurityConfig 수정 #8
  src/main/java/dnd/project/dnd6th7worryrecordservice/config/SecurityConfig.java
Labels: 코드 수정

#77 fix: 유저 Entity에 걱정 Entity OneToMany Mapping #59
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/user/User.java
Labels: 기능 개선

#79 CI/CD: fix: 유저 Entity에 걱정 Entity OneToMany Mapping
  .github/workflows/docker.yml
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/user/User.java
Labels: CI/CD

#80 fix: SpringSecurity, JwtInterceptor 사용 #59
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/AuthController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/config/SecurityConfig.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/config/WebConfig.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/jwt/JwtUtil.java
Labels: 코드 수정

#81 Feature/59 worry locker
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/AuthController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/config/SecurityConfig.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/config/WebConfig.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/jwt/JwtUtil.java
Labels: 코드 수정

#82 CI/CD: fix: SpringSecurity, JwtInterceptor 사용
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/AuthController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/config/SecurityConfig.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/config/WebConfig.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/jwt/JwtUtil.java
Labels: CI/CD

#84 feat: AWS S3 더미 home Img GIF 호출기능 추가 #83
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/aws/S3Util.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/config/AmazonS3Config.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/worry/WorryRepository.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryHomeResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/WorryService.java
Labels: 기능 구현

#85 feat: AWS S3 더미 home Img GIF 호출기능 추가 #83
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/aws/S3Util.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/config/AmazonS3Config.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/worry/WorryRepository.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryHomeResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/WorryService.java
Labels: 기능 구현

#87 CI/CD: fix: SpringSecurity 제거
  build.gradle
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/aws/S3Util.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/config/AmazonS3Config.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/config/JwtConfig.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/config/SecurityConfig.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/config/WebConfig.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/worry/WorryRepository.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryHomeResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/jwt/JwtUtil.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/WorryService.java
  src/main/resources/application.yml
Labels: CI/CD

#91 CI/CD: fix: application.yml S3 설정 추가
  src/main/resources/application.yml
Labels: CI/CD

#94 CI/CD: fix: application.yml DB설정 추가
  src/main/resources/application.yml
Labels: CI/CD

#95 fix: application.yml AWS secret Manager 설정 #83
  src/main/resources/application.yml
Labels: 기능 개선

#96 fix: application.yml AWS secret Manager 설정
  src/main/resources/application.yml
Labels: 기능 개선

#97 CI/CD: fix: application.yml AWS secret Manager 설정
  src/main/resources/application.yml
Labels: CI/CD

#98 feat: home화면 달 GIF 불러오기 구현 #83
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/worry/Worry.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/worry/WorryRepository.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryWriteResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/WorryService.java
Labels: 기능 구현

#100 feat: home화면 달 GIF 불러오기 구현 #83
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/worry/Worry.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/worry/WorryRepository.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryWriteResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/WorryService.java
Labels: 기능 구현

#101 CI/CD: feat: home화면 달 GIF 불러오기 구현
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/worry/Worry.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/worry/WorryRepository.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryWriteResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/WorryService.java
Labels: CI/CD

#102 feat: WorryController Swagger 세팅 #83
  .github/workflows/docker.yml
  .gitignore
  Dockerrun.aws.json
  README.md
  build.gradle
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/AuthController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/HealthCheck.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/aws/S3Util.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/config/AmazonS3Config.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/config/AppConfig.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/config/JwtConfig.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/config/SwaggerConfig.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/controller/UserController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/category/Category.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/category/CategoryRepository.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/user/User.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/user/UserRepository.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/worry/Worry.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/worry/WorryRepository.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/UserRequestDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/UserResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/jwt/JwtPayloadDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/jwt/TokenDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/user/UserRequestDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/user/UserResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/request/WorryRequestDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/request/WorryReviewModifyRequestDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryChatResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryCntResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryHomeResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryReviewResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryWriteResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/jwt/JwtInterceptor.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/jwt/JwtUtil.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/CategoryService.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/KakaoService.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/UserService.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/UserServiceImpl.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/WorryService.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/sql/ddl.sql
  src/main/resources/application.yml
  src/main/resources/bootstrap.yml
  src/test/java/dnd/project/dnd6th7worryrecordservice/Dnd6th7WorryRecordServiceApplicationTests.java
  src/test/java/dnd/project/dnd6th7worryrecordservice/service/UserServiceImplTest.java
  src/test/java/dnd/project/dnd6th7worryrecordservice/singletonTest/RepositorySingletonTest.java
Labels: 기능 구현

#103 Feature/8 swagger setting
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
Labels: 기능 구현

#104 fix: WorryCntResponseDto에 username 추가 #59
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/worry/Worry.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/domain/worry/WorryRepository.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryCntResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryWriteResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/WorryService.java
Labels: 코드 수정

#106 CI/CD: feat,fix: 걱정API 기능 구현 및 수정사항 반영
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryCntResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/WorryService.java
Labels: CI/CD

#107 feat: 걱정API Swagger 설정 추가 #8
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
Labels: 기능 개선

#108 feat: 걱정API Swagger 설정 추가
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
Labels: 기능 개선

#109 CI/CD: feat: 걱정API Swagger 설정 추가
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
Labels: CI/CD

#110 fix: WorryHomeResponseDto 데이터 자료형 변경 #59
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryHomeResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/WorryService.java
Labels: 코드 수정

#111 fix: WorryHomeResponseDto 데이터 자료형 변경
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryHomeResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/WorryService.java
Labels: 코드 수정

#112 CI/CD: fix: WorryHomeResponseDto 데이터 자료형 변경
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryHomeResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/WorryService.java
Labels: CI/CD

#113 fix: 걱정 삭제 API 수정 #59
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/WorryService.java
Labels: 기능 개선

#114 fix: 걱정 삭제 API 수정
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/WorryService.java
Labels: 기능 개선

#115 CI/CD: fix: 걱정 삭제 API 수정
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/WorryService.java
Labels: CI/CD

#116 fix: 지난 걱정 Response 데이터 변경 #59
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryPastResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/WorryService.java
Labels: 기능 개선

#118 CI/CD: fix: 지난 걱정 Response 데이터 변경
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryPastResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/WorryService.java
Labels: CI/CD

#119 fix: 걱정 후기 작성 채팅방 ResponseDto 수정 #59
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryChatResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryCntResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/WorryService.java
Labels: 기능 개선

#120 fix: 걱정 후기 작성 채팅방 ResponseDto 수정
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryChatResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/dto/worry/response/WorryCntResponseDto.java
  src/main/java/dnd/project/dnd6th7worryrecordservice/service/WorryService.java
Labels: 기능 개선

#122 fix: 걱정 후기 입력 OR 수정 API 스웨거 세팅 변경 #8
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
Labels: 코드 수정

#123 fix: 걱정 후기 입력 OR 수정 API 스웨거 세팅 변경 #8
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
Labels: 코드 수정

#124 CI/CD: fix: 걱정 후기 입력 OR 수정 API 스웨거 세팅 변경
  src/main/java/dnd/project/dnd6th7worryrecordservice/api/WorryController.java
Labels: CI/CD
